name = "neualm-infotafel"
main = "worker.js"
compatibility_date = "2024-04-01"

[vars]
ADMIN_PW = "8520"

[[d1_databases]]
binding = "DB"
database_name = "neualm-db-neu"
database_id = "aef2124d-a321-4c24-b5f9-20a73da36c9f"
